import { Translations, Language, LegalArea, AnalysisTone, CaseData } from './types';

export const INITIAL_CASE_DATA: CaseData = {
  title: '',
  jurisdiction: 'Uzbekistan',
  area: LegalArea.CIVIL,
  facts: '',
  tone: AnalysisTone.PROFESSIONAL,
  isDeepAnalysis: false,
  showLegalResolution: true,
};

// Translations for the Legal Area Dropdown
export const LEGAL_AREA_TRANSLATIONS: Record<Language, Record<LegalArea, string>> = {
  en: {
    [LegalArea.ADMINISTRATIVE]: 'Administrative Law',
    [LegalArea.BANKING]: 'Banking & Finance',
    [LegalArea.BANKRUPTCY]: 'Bankruptcy',
    [LegalArea.CIVIL]: 'Civil Law',
    [LegalArea.CONSTITUTIONAL]: 'Constitutional Law',
    [LegalArea.CONTRACT]: 'Contract Law',
    [LegalArea.CORPORATE]: 'Corporate Law',
    [LegalArea.CRIMINAL]: 'Criminal Law',
    [LegalArea.CUSTOMS]: 'Customs Law',
    [LegalArea.FAMILY]: 'Family Law',
    [LegalArea.HOUSING]: 'Housing Law',
    [LegalArea.IMMIGRATION]: 'Immigration Law',
    [LegalArea.INSURANCE]: 'Insurance Law',
    [LegalArea.INTELLECTUAL_PROPERTY]: 'Intellectual Property',
    [LegalArea.INTERNATIONAL]: 'International Law',
    [LegalArea.INVESTMENT]: 'Investment Law',
    [LegalArea.LABOR]: 'Labor Law',
    [LegalArea.PROCEDURAL]: 'Procedural Law',
    [LegalArea.PROPERTY]: 'Property / Real Estate',
    [LegalArea.TAX]: 'Tax Law',
    [LegalArea.TORT]: 'Tort Law'
  },
  uz_lat: {
    [LegalArea.ADMINISTRATIVE]: "Ma'muriy huquq",
    [LegalArea.BANKING]: 'Bank va moliya',
    [LegalArea.BANKRUPTCY]: 'Bankrotlik',
    [LegalArea.CIVIL]: 'Fuqarolik huquqi',
    [LegalArea.CONSTITUTIONAL]: 'Konstitutsiyaviy huquq',
    [LegalArea.CONTRACT]: 'Shartnoma huquqi',
    [LegalArea.CORPORATE]: 'Korporativ huquq',
    [LegalArea.CRIMINAL]: 'Jinoyat huquqi',
    [LegalArea.CUSTOMS]: 'Bojxona huquqi',
    [LegalArea.FAMILY]: 'Oila huquqi',
    [LegalArea.HOUSING]: 'Uy-joy huquqi',
    [LegalArea.IMMIGRATION]: 'Migratsiya huquqi',
    [LegalArea.INSURANCE]: "Sug'urta huquqi",
    [LegalArea.INTELLECTUAL_PROPERTY]: 'Intellektual mulk',
    [LegalArea.INTERNATIONAL]: 'Xalqaro huquq',
    [LegalArea.INVESTMENT]: 'Investitsiya huquqi',
    [LegalArea.LABOR]: 'Mehnat huquqi',
    [LegalArea.PROCEDURAL]: 'Protsessual huquq',
    [LegalArea.PROPERTY]: "Mulk va ko'chmas mulk",
    [LegalArea.TAX]: 'Soliq huquqi',
    [LegalArea.TORT]: 'Delikt huquqi'
  },
  uz_cyr: {
    [LegalArea.ADMINISTRATIVE]: 'Маъмурий ҳуқуқ',
    [LegalArea.BANKING]: 'Банк ва молия',
    [LegalArea.BANKRUPTCY]: 'Банкротлик',
    [LegalArea.CIVIL]: 'Фуқаролик ҳуқуқи',
    [LegalArea.CONSTITUTIONAL]: 'Конституциявий ҳуқуқ',
    [LegalArea.CONTRACT]: 'Шартнома ҳуқуқи',
    [LegalArea.CORPORATE]: 'Корпоратив ҳуқуқ',
    [LegalArea.CRIMINAL]: 'Жиноят ҳуқуқи',
    [LegalArea.CUSTOMS]: 'Божхона ҳуқуқи',
    [LegalArea.FAMILY]: 'Оила ҳуқуқи',
    [LegalArea.HOUSING]: 'Уй-жой ҳуқуқи',
    [LegalArea.IMMIGRATION]: 'Миграция ҳуқуқи',
    [LegalArea.INSURANCE]: 'Суғурта ҳуқуқи',
    [LegalArea.INTELLECTUAL_PROPERTY]: 'Интеллектуал мулк',
    [LegalArea.INTERNATIONAL]: 'Халқаро ҳуқуқ',
    [LegalArea.INVESTMENT]: 'Инвестиция ҳуқуқи',
    [LegalArea.LABOR]: 'Меҳнат ҳуқуқи',
    [LegalArea.PROCEDURAL]: 'Процессуал ҳуқуқ',
    [LegalArea.PROPERTY]: 'Мулк ва кўчмас мулк',
    [LegalArea.TAX]: 'Солиқ ҳуқуқи',
    [LegalArea.TORT]: 'Деликт ҳуқуқи'
  },
  ru: {
    [LegalArea.ADMINISTRATIVE]: 'Административное право',
    [LegalArea.BANKING]: 'Банковское дело и финансы',
    [LegalArea.BANKRUPTCY]: 'Банкротство',
    [LegalArea.CIVIL]: 'Гражданское право',
    [LegalArea.CONSTITUTIONAL]: 'Конституционное право',
    [LegalArea.CONTRACT]: 'Договорное право',
    [LegalArea.CORPORATE]: 'Корпоративное право',
    [LegalArea.CRIMINAL]: 'Уголовное право',
    [LegalArea.CUSTOMS]: 'Таможенное право',
    [LegalArea.FAMILY]: 'Семейное право',
    [LegalArea.HOUSING]: 'Жилищное право',
    [LegalArea.IMMIGRATION]: 'Миграционное право',
    [LegalArea.INSURANCE]: 'Страховое право',
    [LegalArea.INTELLECTUAL_PROPERTY]: 'Интеллектуальная собственность',
    [LegalArea.INTERNATIONAL]: 'Международное право',
    [LegalArea.INVESTMENT]: 'Инвестиционное право',
    [LegalArea.LABOR]: 'Трудовое право',
    [LegalArea.PROCEDURAL]: 'Процессуальное право',
    [LegalArea.PROPERTY]: 'Недвижимость',
    [LegalArea.TAX]: 'Налоговое право',
    [LegalArea.TORT]: 'Деликтное право'
  }
};

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    nav: {
      home: 'Home',
      newCase: 'New Case',
      resources: 'About Us',
      brand: 'Casify',
      langTooltip: 'Change the interface and AI output language.',
      history: 'History',
      signIn: 'Sign In',
      myProfile: 'My Profile',
      settings: 'Settings',
      signOut: 'Sign Out',
    },
    hero: {
      brandName: 'CASIFY',
      title: 'Transform Legal Analysis with Artificial Intelligence',
      subtitle: 'The first academic platform adapted to TSUL standards. Generate professional case studies, risk assessments, and checklists in seconds.',
      cta: 'Start Analysis',
      secondaryCta: 'Quick Draft',
      resourcesBtn: 'Learn More',
    },
    features: {
      deepAnalysis: { title: 'Deep Legal Analysis', desc: 'IRAC structured reasoning based on legal principles.' },
      bilingual: { title: 'Multilingual Support', desc: 'Fluent in Uzbek, Russian, and English.' },
      security: { title: 'Security First', desc: 'Local processing. No external databases. Your client data stays yours.' },
    },
    form: {
      steps: { metadata: 'Metadata', facts: 'Facts', review: 'Review' },
      titleLabel: 'Case Title / Reference',
      jurisdictionLabel: 'Jurisdiction',
      areaLabel: 'Legal Area',
      factsLabel: 'Topic or Case Description',
      factsPlaceholder: 'Enter a legal topic (e.g. "Intellectual property dispute over software code") or specific keywords. The AI will research real-life cases for you.',
      toneLabel: 'Tone',
      depthLabel: 'Analysis Depth',
      generateBtn: 'Research & Generate',
      generating: 'Searching Case Law...',
      piiWarning: 'You are about to generate a legal case study based on the provided facts. Please ensure no sensitive personally identifiable information (PII) is included if not necessary.',
      deepAnalysisLabel: 'Enable Deep Analysis (Slower, more comprehensive)',
      resolutionLabel: 'Include Legal Resolution / Court Outcome',
      tones: {
        professional: 'Professional',
        student: 'Student'
      },
      buttons: {
        nextFacts: 'Next: Facts',
        nextSettings: 'Next: Settings',
        back: 'Back'
      },
      tooltips: {
        title: 'A unique reference or internal case number for your files.',
        jurisdiction: 'Currently limited to Uzbekistan. More regions coming soon.',
        area: 'Helps the AI select the relevant procedural code (e.g., GPK, UPK).',
        facts: 'Enter a topic, keywords, or situation. The AI will use Google Search to find real precedents.',
        tone: 'Student mode explains concepts simply; Professional mode assumes legal knowledge.',
        depth: 'Deep analysis checks more potential rules but takes longer to generate.'
      },
      validation: {
        required: 'This field is required.',
      },
    },
    result: {
      privileged: 'Privileged & Confidential',
      generatedBy: 'Generated by Casify AI',
      summaryHeader: 'Case Details & Summary',
      factsHeader: 'Real-Life Case Pattern',
      analysisHeader: 'Legal Analysis (IRAC)',
      risksHeader: 'Risk Assessment',
      evidenceHeader: 'Evidence Checklist',
      stepsHeader: 'Recommended Next Steps',
      copyBtn: 'Copy JSON',
      copySuccess: 'Copied!',
      printBtn: 'Print / PDF',
      printPreparing: 'Preparing...',
      newCaseBtn: 'New Case',
      sourcesHeader: 'Legal Sources & References',
      practiceAi: {
        title: 'Practice AI',
        greeting: 'I am here to assist you with legal research and case analysis.'
      }
    },
    about: {
      tagline: 'The Future of Jurisprudence',
      mission: { title: 'Our Mission', text: 'To digitize legal workflows and empower lawyers with instant, accurate analysis, adapted to the highest professional standards.' },
      tech: { title: 'AI Technology', text: 'Powered by advanced Google Gemini 3 Pro models, the system creates unique analyses tailored to the needs of every legal professional.' },
      team: { title: 'Developer', text: 'This platform was created by Oxforder LLC based on principles of academic and professional excellence.' },
    },
    footer: {
      platformHeader: 'Platform',
      disclaimerHeader: 'Legal Disclaimer',
      disclaimer: 'Casify is an AI-powered legal research assistant. Content generated is for informational purposes only and does not constitute professional legal advice or attorney-client privilege.',
      copyright: '© 2026 Oxforder LLC. All Rights Reserved.',
      links: { privacy: 'Privacy Policy', terms: 'Terms of Service', contact: 'Contact Support' }
    },
    history: {
      title: 'Case History',
      subtitle: 'All previously analyzed cases stored locally in your browser',
      empty: { title: 'No cases yet', desc: 'Once you analyze a case, it will appear here for quick reference.', btn: 'Analyze Your First Case' },
      searchPlaceholder: 'Search by title or legal area...',
      casesLabel: 'cases',
      clearAll: 'Clear All',
      open: 'Open',
      deleteConfirm: 'Delete?',
      yes: 'Yes',
      cancel: 'Cancel',
    },
    aiFeatures: {
      header: 'AI Features',
      flashcards: { title: 'Study Flashcards', desc: 'Generate & review cards' },
      counterarguments: { title: 'Counterarguments', desc: 'Opposing party simulation', analyzing: 'Analyzing...', show: 'Show Counter', hide: 'Hide Counter' },
      draftDocument: { title: 'Draft Document', desc: 'Complaint, motion, opinion' },
      audioBriefing: { title: 'Listen to Briefing', desc: 'AI audio summary', generating: 'Generating...', stop: 'Stop Briefing' },
      timeline: { title: 'Case Timeline', desc: 'Deadlines & key dates', building: 'Building...', show: 'Show Timeline', hide: 'Hide Timeline' },
    },
    profile: {
      title: 'My Profile',
      casesAnalyzed: 'Cases Analyzed',
      memberSince: 'Member Since',
      account: 'Account',
      profileInfo: 'Profile Information',
      editSettings: 'Edit Settings',
      viewHistory: 'View History',
      signOut: 'Sign Out',
      fields: { name: 'Full Name', email: 'Email Address', role: 'Role', institution: 'Institution', specialization: 'Specialization' },
      notSignedIn: 'Not signed in.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Customize your Casify profile',
      account: 'Account',
      displayName: 'Display Name',
      role: 'Role',
      institution: 'Institution / Organization',
      specialization: 'Legal Specialization',
      selectSpec: 'Select specialization',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      savedSuccess: 'Saved successfully!',
      notSignedIn: 'Please sign in to access settings.',
    },
    generating: {
      title: 'Analyzing Case',
      subtitle: 'Powered by Gemini AI',
      stages: [
        { label: 'Reading case facts...', sub: 'Extracting key parties, events, and context' },
        { label: 'Identifying legal issues...', sub: 'Mapping claims to applicable legal standards' },
        { label: 'Building IRAC analysis...', sub: 'Issue · Rule · Application · Conclusion' },
        { label: 'Consulting legal sources...', sub: 'Searching statutes, case law, and precedents' },
        { label: 'Assessing risks & evidence...', sub: 'Compiling checklist and exposure points' },
        { label: 'Finalizing memorandum...', sub: 'Structuring the full legal memo' },
      ],
      stepOf: 'Step {n} of {total}',
    },
    flashcards: {
      title: 'Flashcards',
      generated: 'cards generated',
      aiCards: 'AI-generated study cards',
      generateBtn: 'Generate Flashcards',
      generating: 'Generating cards...',
      studyMode: 'Study Mode',
      gridView: 'Grid View',
      cardOf: 'Card {n} of {total}',
      reset: 'Reset',
      clickToFlip: 'Click to flip',
      showingAnswer: 'Showing answer',
      question: 'Question',
      answer: 'Answer',
      promptTitle: 'Generate study flashcards',
      promptDesc: 'AI will create 12-15 cards covering key terms, IRAC elements, legal principles, and risks from this case.',
      pdf: 'PDF',
    },
  },
  uz_lat: {
    nav: {
      home: 'Bosh sahifa',
      newCase: 'Yangi kazus',
      resources: 'Biz haqimizda',
      brand: 'Casify',
      langTooltip: 'Interfeys va AI tahlil tilini o\'zgartirish.',
      history: 'Tarix',
      signIn: 'Kirish',
      myProfile: 'Mening profilim',
      settings: 'Sozlamalar',
      signOut: 'Chiqish',
    },
    hero: {
      brandName: 'CASIFY',
      title: "Yuridik ta'limni sun'iy intellekt bilan o'zgartiring",
      subtitle: "TDYU standartlariga moslashtirilgan birinchi akademik platforma. Soniyalar ichida mukammal darslar, sud ishlari tahlili va huquqiy doktrinalarni o'rganing.",
      cta: "O'qishni boshlash",
      secondaryCta: 'Tezkor tahlil',
      resourcesBtn: 'Batafsil',
    },
    features: {
      deepAnalysis: { title: 'Chuqur yuridik tahlil', desc: "Yuridik tamoyillarga asoslangan IRAC tuzilmasi bo'yicha tahlil." },
      bilingual: { title: 'Ko‘p tilli', desc: "O'zbek, rus va Ingliz tillarida ravon." },
      security: { title: 'Xavfsizlik birinchi o‘rinda', desc: 'Mahalliy qayta ishlash. Tashqi bazalar yo‘q. Sizning ma\'lumotlaringiz o‘zingizda qoladi.' },
    },
    form: {
      steps: { metadata: 'Ma\'lumotlar', facts: 'Faktlar', review: 'Ko‘rib chiqish' },
      titleLabel: 'Ish nomi / havola',
      jurisdictionLabel: 'Yurisdiksiya',
      areaLabel: 'Huquq sohasi',
      factsLabel: 'Mavzu yoki kazus tavsifi',
      factsPlaceholder: 'Yuridik mavzuni kiriting (masalan, "Dasturiy ta\'minot bo\'yicha mualliflik huquqi") yoki kalit so\'zlar. AI siz uchun real sud ishlarini qidirib topadi.',
      toneLabel: 'Ohang',
      depthLabel: 'Tahlil chuqurligi',
      generateBtn: 'Qidirish va tahlil qilish',
      generating: 'Sud amaliyoti qidirilmoqda...',
      piiWarning: "Siz taqdim etilgan faktlar asosida yuridik kazus tahlili va amaliyotini o'rganmoqchisiz. Iltimos, zarurat bo'lmasa, shaxsga doir maxfiy ma'lumotlar (PII) kiritilmaganligiga ishonch hosil qiling.",
      deepAnalysisLabel: "Chuqur tahlilni yoqish (sekinroq, keng qamrovli)",
      resolutionLabel: "Sud qarori / Yakuniy yechimni ko'rsatish",
      tones: {
        professional: 'Professional',
        student: 'Talaba'
      },
      buttons: {
        nextFacts: 'Keyingisi: Faktlar',
        nextSettings: 'Keyingisi: Sozlamalar',
        back: 'Orqaga'
      },
      tooltips: {
        title: 'Fayllaringiz uchun noyob havola yoki ichki ish raqami.',
        jurisdiction: 'Hozirda faqat O\'zbekiston bilan cheklangan.',
        area: 'Sun\'iy intellektga tegishli protsessual kodeksni tanlashda yordam beradi.',
        facts: 'Mavzu yoki kalit so\'zlarni kiriting. AI Google orqali real presedentlarni topadi.',
        tone: 'Talaba rejimi tushunchalarni sodda tushuntiradi; Professional rejim yuridik bilimni nazarda tutadi.',
        depth: 'Chuqur tahlil ko\'proq qoidalarni tekshiradi, lekin yaratish uchun ko\'proq vaqt oladi.'
      },
      validation: {
        required: 'Ushbu maydon to\'ldirilishi shart.',
      },
    },
    result: {
      privileged: 'Maxfiy va ishonchli',
      generatedBy: 'Casify AI tomonidan yaratilgan',
      summaryHeader: 'Kazus tafsilotlari va Xulosa',
      factsHeader: 'Real sud ishi tafsilotlari',
      analysisHeader: 'Yuridik tahlil (IRAC)',
      risksHeader: 'Risklarni baholash',
      evidenceHeader: 'Dalillar ro‘yxati',
      stepsHeader: 'Tavsiya etilgan keyingi qadamlar',
      copyBtn: 'Nusxalash',
      copySuccess: 'Nusxalandi!',
      printBtn: 'Chop etish',
      printPreparing: 'Tayyorlanmoqda...',
      newCaseBtn: 'Yangi ish',
      sourcesHeader: 'Manbalar va havolalar',
      practiceAi: {
        title: 'Practice AI',
        greeting: 'Men sizga yuridik tadqiqot va kazus tahlilida yordam berish uchun shu yerdaman.'
      }
    },
    about: {
      tagline: 'Kelajak yurisprudensiyasi',
      mission: { title: 'Bizning missiyamiz', text: 'Yuridik sohani raqamlashtirish va huquqshunoslarga eng so\'nggi texnologiyalar yordamida chuqur va aniq tahlil taqdim etish.' },
      tech: { title: 'AI texnologiyasi', text: 'Google Gemini 3 Pro modellari asosida ishlovchi tizim har bir huquqshunosning ehtiyojiga moslashtirilgan noyob yechimlarni yaratadi.' },
      team: { title: 'Ishlab chiqaruvchi', text: 'Ushbu platforma Oxforder MCHJ tomonidan akademik mukammallik tamoyillari asosida yaratilgan.' },
    },
    footer: {
      platformHeader: 'Platforma',
      disclaimerHeader: 'Yuridik Ogohlantirish',
      disclaimer: "Casify - bu sun'iy intellektga asoslangan yuridik tadqiqot yordamchisi. Yaratilgan tarkib faqat ma'lumot olish uchun mo'ljallangan va professional yuridik maslahat hisoblanmaydi.",
      copyright: "© 2026 Oxforder MCHJ. Barcha huquqlar himoyalangan.",
      links: { privacy: 'Maxfiylik siyosati', terms: 'Foydalanish shartlari', contact: "Qo'llab-quvvatlash" }
    },
    history: {
      title: 'Kazuslar tarixi',
      subtitle: 'Brauzeringizda mahalliy saqlangan barcha tahlil qilingan kazuslar',
      empty: { title: 'Hozircha kazuslar yo\'q', desc: 'Kazusni tahlil qilganingizda, u tez murojaat uchun bu yerda ko\'rinadi.', btn: 'Birinchi kazusni tahlil qilish' },
      searchPlaceholder: 'Sarlavha yoki huquq sohasi bo\'yicha qidirish...',
      casesLabel: 'ta kazus',
      clearAll: 'Hammasini o\'chirish',
      open: 'Ochish',
      deleteConfirm: 'O\'chirilsinmi?',
      yes: 'Ha',
      cancel: 'Bekor qilish',
    },
    aiFeatures: {
      header: 'AI xususiyatlari',
      flashcards: { title: 'Flesh kartalar', desc: 'Kartalar yaratish va takrorlash' },
      counterarguments: { title: 'Qarshi dalillar', desc: 'Qarama-qarshi tomon simulyatsiyasi', analyzing: 'Tahlil qilinmoqda...', show: 'Ko\'rsatish', hide: 'Yashirish' },
      draftDocument: { title: 'Hujjat tayyorlash', desc: 'Da\'vonom, ariza, xulosa' },
      audioBriefing: { title: 'Tinglab o\'qish', desc: 'AI audio xulosasi', generating: 'Yaratilmoqda...', stop: 'To\'xtatish' },
      timeline: { title: 'Kazus vaqt jadvali', desc: 'Muddatlar va muhim sanalar', building: 'Qurilmoqda...', show: 'Ko\'rsatish', hide: 'Yashirish' },
    },
    profile: {
      title: 'Mening profilim',
      casesAnalyzed: 'Tahlil qilingan kazuslar',
      memberSince: 'A\'zolik sanasi',
      account: 'Hisob',
      profileInfo: 'Profil ma\'lumotlari',
      editSettings: 'Sozlamalarni tahrirlash',
      viewHistory: 'Tarixni ko\'rish',
      signOut: 'Chiqish',
      fields: { name: 'To\'liq ism', email: 'Elektron pochta', role: 'Lavozim', institution: 'Muassasa', specialization: 'Mutaxassislik' },
      notSignedIn: 'Tizimga kirilmagan.',
    },
    settings: {
      title: 'Sozlamalar',
      subtitle: 'Casify profilingizni sozlang',
      account: 'Hisob',
      displayName: 'Ko\'rsatiladigan ism',
      role: 'Lavozim',
      institution: 'Muassasa / Tashkilot',
      specialization: 'Huquqiy mutaxassislik',
      selectSpec: 'Mutaxassislikni tanlang',
      saveChanges: 'Saqlash',
      saving: 'Saqlanmoqda...',
      savedSuccess: 'Muvaffaqiyatli saqlandi!',
      notSignedIn: 'Sozlamalarga kirish uchun tizimga kiring.',
    },
    generating: {
      title: 'Kazus tahlil qilinmoqda',
      subtitle: 'Gemini AI tomonidan',
      stages: [
        { label: 'Kazus faktlari o\'qilmoqda...', sub: 'Asosiy tomonlar, voqealar va kontekst ajratilmoqda' },
        { label: 'Yuridik masalalar aniqlanmoqda...', sub: 'Da\'volar qonuniy standartlarga mos qo\'yilmoqda' },
        { label: 'IRAC tahlili qurilmoqda...', sub: 'Masala · Qoida · Qo\'llash · Xulosa' },
        { label: 'Yuridik manbalar tekshirilmoqda...', sub: 'Qonunlar, sud amaliyoti va presedentlar qidirilmoqda' },
        { label: 'Risklar va dalillar baholanmoqda...', sub: 'Ro\'yxat va ta\'sir nuqtalari tuzilmoqda' },
        { label: 'Memorandum yakunlanmoqda...', sub: 'To\'liq yuridik memo tuzilmoqda' },
      ],
      stepOf: '{n} / {total} bosqich',
    },
    flashcards: {
      title: 'Flesh kartalar',
      generated: 'ta karta yaratildi',
      aiCards: 'AI tomonidan yaratilgan o\'quv kartalari',
      generateBtn: 'Flesh kartalar yaratish',
      generating: 'Kartalar yaratilmoqda...',
      studyMode: 'O\'qish rejimi',
      gridView: 'Tarmoq ko\'rinishi',
      cardOf: '{n} / {total} karta',
      reset: 'Qayta boshlash',
      clickToFlip: 'Ag\'darish uchun bosing',
      showingAnswer: 'Javob ko\'rsatilmoqda',
      question: 'Savol',
      answer: 'Javob',
      promptTitle: 'O\'quv flesh kartalarini yaratish',
      promptDesc: 'AI bu kazusdan asosiy atamalar, IRAC elementlari, huquqiy tamoyillar va risklar bo\'yicha 12-15 ta karta yaratadi.',
      pdf: 'PDF',
    },
  },
  uz_cyr: {
    nav: {
      home: 'Бош саҳифа',
      newCase: 'Янги казус',
      resources: 'Биз ҳақимизда',
      brand: 'Casify',
      langTooltip: 'Интерфейс ва АИ таҳлил тилини ўзгартириш.',
      history: 'Тарих',
      signIn: 'Кириш',
      myProfile: 'Менинг профилим',
      settings: 'Созламалар',
      signOut: 'Чиқиш',
    },
    hero: {
      brandName: 'CASIFY',
      title: 'Юридик таълимни сунъий интеллект билан ўзгартиринг',
      subtitle: 'ТДЮУ стандартларига мослаштирилган биринчи академик платформа. Сониялар ичида мукаммал дарслар, суд ишлари таҳлили ва ҳуқуқий доктриналарни ўрганинг.',
      cta: 'Ўқишни бошлаш',
      secondaryCta: 'Тезкор таҳлил',
      resourcesBtn: 'Батафсил',
    },
    features: {
      deepAnalysis: { title: 'Чуқур юридик таҳлил', desc: 'Ҳуқуқий тамойилларга асосланган IRAC тузилмаси бўйича таҳлил.' },
      bilingual: { title: 'Кўп тилли', desc: 'Ўзбек, Рус ва Инглиз тилларида равон.' },
      security: { title: 'Хавфсизлик биринчи ўринда', desc: 'Маҳаллий қайта ишлаш. Ташқи базалар йўқ. Сизнинг маълумотларингиз ўзингизда қолади.' },
    },
    form: {
      steps: { metadata: 'Маълумотлар', facts: 'Фактлар', review: 'Кўриб чиқиш' },
      titleLabel: 'Иш номи / ҳавола',
      jurisdictionLabel: 'Юрисдикция',
      areaLabel: 'Ҳуқуқ соҳаси',
      factsLabel: 'Мавзу ёки казус тавсифи',
      factsPlaceholder: 'Юридик мавзуни киритинг (масалан, "Дастурий таъминот бўйича муаллифлик ҳуқуқи") ёки калит сўзлар. АИ сиз учун реал суд ишларини қидириб топади.',
      toneLabel: 'Оҳанг',
      depthLabel: 'Таҳлил чуқурлиги',
      generateBtn: 'Қидириш ва таҳлил қилиш',
      generating: 'Суд амалиёти қидирилмоқда...',
      piiWarning: 'Сиз тақдим этилган фактлар асосида юридик казус таҳлили ва амалиётини ўрганмоқчисиз. Илтимос, зарурат бўлмаса, шахсга доир махфий маълумотлар (PII) киритилмаганлигига ишонч ҳосил қилинг.',
      deepAnalysisLabel: 'Чуқур таҳлилни ёқиш (секинроқ, кенг қамровли)',
      resolutionLabel: 'Суд қарори / Якуний ечимни кўрсатиш',
      tones: {
        professional: 'Профессионал',
        student: 'Талаба'
      },
      buttons: {
        nextFacts: 'Кейингиси: Фактлар',
        nextSettings: 'Кейингиси: Созламалар',
        back: 'Орқага'
      },
      tooltips: {
        title: 'Файлларингиз учун ноёб ҳавола ёки ички иш рақами.',
        jurisdiction: 'Ҳозирда фақат Ўзбекистон билан чекланган.',
        area: 'Сунъий интеллектга тегишли процессуал кодексни танлашда ёрдам беради.',
        facts: 'Мавзу ёки калит сўзларни киритинг. АИ Google орқали реал преседентларни топади.',
        tone: 'Талаба режими тушунчаларни содда тушунтиради; Профессионал режим юридик билимни назарда тутади.',
        depth: 'Чуқур таҳлил кўпроқ қоидаларни текширади, лекин яратиш учун кўпроқ вақт олади.'
      },
      validation: {
        required: 'Ушбу майдон тўлдирилиши шарт.',
      },
    },
    result: {
      privileged: 'Махфий ва ишончли',
      generatedBy: 'Casify AI томонидан яратилган',
      summaryHeader: 'Казус тафсилотлари ва Хулоса',
      factsHeader: 'Реал суд иши тафсилотлари',
      analysisHeader: 'Юридик таҳлил (IRAC)',
      risksHeader: 'Рискларни баҳолаш',
      evidenceHeader: 'Далиллар рўйхати',
      stepsHeader: 'Тавсия этилган кейинги қадамлар',
      copyBtn: 'Нусхалаш',
      copySuccess: 'Нусхаланди!',
      printBtn: 'Чоп этиш',
      printPreparing: 'Тайёрланмоқда...',
      newCaseBtn: 'Янги иш',
      sourcesHeader: 'Манбалар ва ҳаволалар',
      practiceAi: {
        title: 'Practice AI',
        greeting: 'Мен сизга юридик тадқиқот ва казус таҳлилида ёрдам бериш учун шу ердаман.'
      }
    },
    about: {
      tagline: 'Келажак юриспруденцияси',
      mission: { title: 'Бизнинг миссиямиз', text: 'Юридик соҳани рақамлаштириш ва ҳуқуқшуносларга энг сўнгги технологиялар ёрдамида чуқур ва аниқ таҳлил тақдим этиш.' },
      tech: { title: 'AI технологияси', text: 'Google Gemini 3 Pro моделлари асосида ишловчи тизим ҳар бир ҳуқуқшуноснинг эҳтиёжига мослаштирилган ноёб ечимларни яратади.' },
      team: { title: 'Ишлаб чиқарувчи', text: 'Ушбу платформа Oxforder МЧЖ томонидан академик мукаммаллик тамойиллари асосида яратилган.' },
    },
    footer: {
      platformHeader: 'Платформа',
      disclaimerHeader: 'Юридик Огоҳлантириш',
      disclaimer: "Casify - бу сунъий интеллектга асосланган юридик тадқиқот ёрдамчиси. Яратилган таркиб фақат маълумот олиш учун мўлжалланган ва профессионал юридик маслаҳат ҳисобланмайди.",
      copyright: "© 2026 Oxforder МЧЖ. Барча ҳуқуқлар ҳимояланган.",
      links: { privacy: 'Махфийлик сиёсати', terms: 'Фойдаланиш шартлари', contact: "Қўллаб-қувватлаш" }
    },
    history: {
      title: 'Казуслар тарихи',
      subtitle: 'Браузерингизда маҳаллий сақланган барча таҳлил қилинган казуслар',
      empty: { title: 'Ҳозирча казуслар йўқ', desc: 'Казусни таҳлил қилганингизда, у тез мурожаат учун бу ерда кўринади.', btn: 'Биринчи казусни таҳлил қилиш' },
      searchPlaceholder: 'Сарлавҳа ёки ҳуқуқ соҳаси бўйича қидириш...',
      casesLabel: 'та казус',
      clearAll: 'Ҳаммасини ўчириш',
      open: 'Очиш',
      deleteConfirm: 'Ўчирилсинми?',
      yes: 'Ҳа',
      cancel: 'Бекор қилиш',
    },
    aiFeatures: {
      header: 'AI хусусиятлари',
      flashcards: { title: 'Флеш карталар', desc: 'Карталар яратиш ва такрорлаш' },
      counterarguments: { title: 'Қарши далиллар', desc: 'Қарама-қарши томон симуляцияси', analyzing: 'Таҳлил қилинмоқда...', show: 'Кўрсатиш', hide: 'Яшириш' },
      draftDocument: { title: 'Ҳужжат тайёрлаш', desc: 'Даъвонома, ариза, хулоса' },
      audioBriefing: { title: 'Тинглаб ўқиш', desc: 'AI аудио хулосаси', generating: 'Яратилмоқда...', stop: 'Тўхтатиш' },
      timeline: { title: 'Казус вақт жадвали', desc: 'Муддатлар ва муҳим санаалар', building: 'Қурилмоқда...', show: 'Кўрсатиш', hide: 'Яшириш' },
    },
    profile: {
      title: 'Менинг профилим',
      casesAnalyzed: 'Таҳлил қилинган казуслар',
      memberSince: 'Аъзолик санаси',
      account: 'Ҳисоб',
      profileInfo: 'Профил маълумотлари',
      editSettings: 'Созламаларни таҳрирлаш',
      viewHistory: 'Тарихни кўриш',
      signOut: 'Чиқиш',
      fields: { name: 'Тўлиқ исм', email: 'Электрон почта', role: 'Лавозим', institution: 'Муассаса', specialization: 'Мутахассислик' },
      notSignedIn: 'Тизимга кирилмаган.',
    },
    settings: {
      title: 'Созламалар',
      subtitle: 'Casify профилингизни созланг',
      account: 'Ҳисоб',
      displayName: 'Кўрсатиладиган исм',
      role: 'Лавозим',
      institution: 'Муассаса / Ташкилот',
      specialization: 'Ҳуқуқий мутахассислик',
      selectSpec: 'Мутахассисликни танланг',
      saveChanges: 'Сақлаш',
      saving: 'Сақланмоқда...',
      savedSuccess: 'Муваффақиятли сақланди!',
      notSignedIn: 'Созламаларга кириш учун тизимга киринг.',
    },
    generating: {
      title: 'Казус таҳлил қилинмоқда',
      subtitle: 'Gemini AI томонидан',
      stages: [
        { label: 'Казус фактлари ўқилмоқда...', sub: 'Асосий томонлар, воқеалар ва контекст ажратилмоқда' },
        { label: 'Юридик масалалар аниқланмоқда...', sub: 'Даъволар қонуний стандартларга мос қўйилмоқда' },
        { label: 'IRAC таҳлили қурилмоқда...', sub: 'Масала · Қоида · Қўллаш · Хулоса' },
        { label: 'Юридик манбалар текширилмоқда...', sub: 'Қонунлар, суд амалиёти ва преседентлар қидирилмоқда' },
        { label: 'Рисклар ва далиллар баҳоланмоқда...', sub: 'Рўйхат ва таъсир нуқталари тузилмоқда' },
        { label: 'Меморандум якунланмоқда...', sub: 'Тўлиқ юридик мемо тузилмоқда' },
      ],
      stepOf: '{n} / {total} босқич',
    },
    flashcards: {
      title: 'Флеш карталар',
      generated: 'та карта яратилди',
      aiCards: 'AI томонидан яратилган ўқув карталари',
      generateBtn: 'Флеш карталар яратиш',
      generating: 'Карталар яратилмоқда...',
      studyMode: 'Ўқиш режими',
      gridView: 'Тармоқ кўриниши',
      cardOf: '{n} / {total} карта',
      reset: 'Қайта бошлаш',
      clickToFlip: 'Ағдариш учун босинг',
      showingAnswer: 'Жавоб кўрсатилмоқда',
      question: 'Савол',
      answer: 'Жавоб',
      promptTitle: 'Ўқув флеш карталарини яратиш',
      promptDesc: 'AI бу казусдан асосий атамалар, IRAC элементлари, ҳуқуқий тамойиллар ва рисклар бўйича 12-15 та карта яратади.',
      pdf: 'PDF',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      newCase: 'Новое дело',
      resources: 'О Нас',
      brand: 'Casify',
      langTooltip: 'Изменить язык интерфейса и вывода ИИ.',
      history: 'История',
      signIn: 'Войти',
      myProfile: 'Мой профиль',
      settings: 'Настройки',
      signOut: 'Выйти',
    },
    hero: {
      brandName: 'CASIFY',
      title: 'Трансформируйте юридическое образование с помощью ИИ',
      subtitle: 'Первая академическая платформа, адаптированная к стандартам ТГЮУ. Создавайте профессиональные кейс-стади, оценки рисков и чек-листы за считанные секунды.',
      cta: 'Начать обучение',
      secondaryCta: 'Быстрый анализ',
      resourcesBtn: 'Подробнее',
    },
    features: {
      deepAnalysis: { title: 'Глубокий юридический анализ', desc: 'Структурированное обоснование IRAC на основе правовых принципов.' },
      bilingual: { title: 'Многоязычная поддержка', desc: 'Свободное владение узбекским, русским и английским языками.' },
      security: { title: 'Безопасность прежде всего', desc: 'Локальная обработка. Никаких внешних баз данных.' },
    },
    form: {
      steps: { metadata: 'Метаданные', facts: 'Факты', review: 'Проверка' },
      titleLabel: 'Название дела / ссылка',
      jurisdictionLabel: 'Юрисдикция',
      areaLabel: 'Область права',
      factsLabel: 'Тема или описание ситуации',
      factsPlaceholder: 'Введите юридическую тему (например, "Авторское право на ПО") или ключевые слова. ИИ найдет реальные судебные дела для вас.',
      toneLabel: 'Тон',
      depthLabel: 'Глубина анализа',
      generateBtn: 'Найти и создать меморандум',
      generating: 'Поиск судебной практики...',
      piiWarning: 'Вы собираетесь создать юридический анализ (кейс-стади) на основе предоставленных фактов. Пожалуйста, убедитесь, что конфиденциальная личная информация (PII) не включена без необходимости.',
      deepAnalysisLabel: 'Включить глубокий анализ (медленнее, более подробно)',
      resolutionLabel: 'Включить решение суда / Итоговый исход',
      tones: {
        professional: 'Профессиональный',
        student: 'Студент'
      },
      buttons: {
        nextFacts: 'Далее: Факты',
        nextSettings: 'Далее: Настройки',
        back: 'Назад'
      },
      tooltips: {
        title: 'Уникальная ссылка или внутренний номер дела для ваших файлов.',
        jurisdiction: 'В настоящее время ограничено Узбекистаном. Скоро будут добавлены другие регионы.',
        area: 'Помогает ИИ выбрать соответствующий процессуальный кодекс (например, ГПК, УПК).',
        facts: 'Введите тему или ключевые слова. ИИ использует Google для поиска реальных прецедентов.',
        tone: 'Режим студента объясняет просто; Профессиональный режим предполагает юридические знания.',
        depth: 'Глубокий анализ проверяет больше правил и прецедентов, но занимает больше времени.'
      },
      validation: {
        required: 'Это поле обязательно.',
      },
    },
    result: {
      privileged: 'Конфиденциально и привилегированно',
      generatedBy: 'Сгенерировано Casify AI',
      summaryHeader: 'Детали дела и Резюме',
      factsHeader: 'Обстоятельства реального дела',
      analysisHeader: 'Юридический анализ (IRAC)',
      risksHeader: 'Оценка рисков',
      evidenceHeader: 'Чек-лист доказательств',
      stepsHeader: 'Рекомендуемые шаги',
      copyBtn: 'Копировать JSON',
      copySuccess: 'Скопировано!',
      printBtn: 'Печать / PDF',
      printPreparing: 'Подготовка...',
      newCaseBtn: 'Новое дело',
      sourcesHeader: 'Источники и ссылки',
      practiceAi: {
        title: 'Practice AI',
        greeting: 'Я здесь, чтобы помочь вам с юридическими исследованиями и анализом дел.'
      }
    },
    about: {
      tagline: 'Юриспруденция будущего',
      mission: { title: 'Наша миссия', text: 'Оцифровать юридические процессы и предоставить юристам глубокий и точный анализ с использованием новейших технологий.' },
      tech: { title: 'Технология ИИ', text: 'Система, работающая на моделях Google Gemini 3 Pro, создает уникальные решения, адаптированные под нужды каждого юриста.' },
      team: { title: 'Разработчик', text: 'Эта платформа была создана ООО Oxforder на основе принципов академического совершенства.' },
    },
    footer: {
      platformHeader: 'Платформа',
      disclaimerHeader: 'Юридический отказ',
      disclaimer: "Casify — это помощник по юридическим исследованиям на базе ИИ. Генерируемый контент предназначен только для информационных целей и не является профессиональной юридической консультацией.",
      copyright: "© 2026 Oxforder LLC. Все права защищены.",
      links: { privacy: 'Политика конфиденциальности', terms: 'Условия использования', contact: 'Поддержка' }
    },
    history: {
      title: 'История дел',
      subtitle: 'Все ранее проанализированные дела, сохранённые в браузере',
      empty: { title: 'Дел пока нет', desc: 'После анализа дела оно появится здесь для быстрого доступа.', btn: 'Проанализировать первое дело' },
      searchPlaceholder: 'Поиск по названию или области права...',
      casesLabel: 'дел',
      clearAll: 'Очистить всё',
      open: 'Открыть',
      deleteConfirm: 'Удалить?',
      yes: 'Да',
      cancel: 'Отмена',
    },
    aiFeatures: {
      header: 'AI-функции',
      flashcards: { title: 'Флеш-карточки', desc: 'Создать и изучить карточки' },
      counterarguments: { title: 'Контраргументы', desc: 'Симуляция противоположной стороны', analyzing: 'Анализ...', show: 'Показать', hide: 'Скрыть' },
      draftDocument: { title: 'Черновик документа', desc: 'Иск, ходатайство, заключение' },
      audioBriefing: { title: 'Аудио-брифинг', desc: 'Краткое резюме от ИИ', generating: 'Генерация...', stop: 'Остановить' },
      timeline: { title: 'Хронология дела', desc: 'Сроки и ключевые даты', building: 'Создание...', show: 'Показать', hide: 'Скрыть' },
    },
    profile: {
      title: 'Мой профиль',
      casesAnalyzed: 'Проанализировано дел',
      memberSince: 'Дата регистрации',
      account: 'Аккаунт',
      profileInfo: 'Информация профиля',
      editSettings: 'Настройки профиля',
      viewHistory: 'История дел',
      signOut: 'Выйти',
      fields: { name: 'Полное имя', email: 'Эл. почта', role: 'Роль', institution: 'Организация', specialization: 'Специализация' },
      notSignedIn: 'Вы не вошли в систему.',
    },
    settings: {
      title: 'Настройки',
      subtitle: 'Настройте ваш профиль Casify',
      account: 'Аккаунт',
      displayName: 'Отображаемое имя',
      role: 'Роль',
      institution: 'Организация / Учреждение',
      specialization: 'Правовая специализация',
      selectSpec: 'Выберите специализацию',
      saveChanges: 'Сохранить',
      saving: 'Сохранение...',
      savedSuccess: 'Успешно сохранено!',
      notSignedIn: 'Войдите в систему для доступа к настройкам.',
    },
    generating: {
      title: 'Анализ дела',
      subtitle: 'На базе Gemini AI',
      stages: [
        { label: 'Чтение фактов дела...', sub: 'Извлечение сторон, событий и контекста' },
        { label: 'Выявление правовых вопросов...', sub: 'Сопоставление требований с правовыми стандартами' },
        { label: 'Построение анализа IRAC...', sub: 'Вопрос · Норма · Применение · Вывод' },
        { label: 'Консультация юридических источников...', sub: 'Поиск законов, судебной практики и прецедентов' },
        { label: 'Оценка рисков и доказательств...', sub: 'Составление чек-листа и точек воздействия' },
        { label: 'Завершение меморандума...', sub: 'Структурирование полного юридического memo' },
      ],
      stepOf: 'Шаг {n} из {total}',
    },
    flashcards: {
      title: 'Флеш-карточки',
      generated: 'карточек создано',
      aiCards: 'Учебные карточки от ИИ',
      generateBtn: 'Создать карточки',
      generating: 'Создание карточек...',
      studyMode: 'Режим изучения',
      gridView: 'Сетка',
      cardOf: 'Карточка {n} из {total}',
      reset: 'Сбросить',
      clickToFlip: 'Нажмите для переворота',
      showingAnswer: 'Показан ответ',
      question: 'Вопрос',
      answer: 'Ответ',
      promptTitle: 'Создать учебные карточки',
      promptDesc: 'ИИ создаст 12-15 карточек с ключевыми терминами, элементами IRAC, правовыми принципами и рисками по данному делу.',
      pdf: 'PDF',
    },
  },
};