import React, { useState } from 'react';
import { Flashcard, LegalMemo, CaseData, Language } from '../types';
import { generateFlashcards } from '../services/geminiService';
import { X, Loader2, ChevronLeft, ChevronRight, RotateCcw, Layers, Download } from 'lucide-react';

interface FlashcardsModalProps {
  memo: LegalMemo;
  caseData: CaseData;
  lang: Language;
  onClose: () => void;
}

const FlashcardsModal: React.FC<FlashcardsModalProps> = ({ memo, caseData, lang, onClose }) => {
  const [cards, setCards] = useState<Flashcard[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [viewMode, setViewMode] = useState<'grid' | 'study'>('study');

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await generateFlashcards(memo, caseData, lang);
      setCards(result);
      setCurrentIdx(0);
      setIsFlipped(false);
    } catch (e: any) {
      setError(e.message || 'Failed to generate flashcards.');
    } finally {
      setIsLoading(false);
    }
  };

  const goNext = () => {
    setIsFlipped(false);
    setTimeout(() => setCurrentIdx(i => Math.min(i + 1, cards.length - 1)), 150);
  };

  const goPrev = () => {
    setIsFlipped(false);
    setTimeout(() => setCurrentIdx(i => Math.max(i - 1, 0)), 150);
  };

  const handlePrintCards = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Flashcards — ${memo.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Merriweather:wght@700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', Arial, sans-serif; background: #f8fafc; color: #1e293b; padding: 32px; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #d97706; }
    .header h1 { font-family: 'Merriweather', Georgia, serif; font-size: 22pt; color: #0f172a; margin-bottom: 6px; }
    .header p { font-size: 10pt; color: #64748b; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .card { background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 6px rgba(0,0,0,0.08); page-break-inside: avoid; border: 1px solid #e2e8f0; }
    .card-front { background: #0f172a; color: white; padding: 16px 20px; }
    .card-num { font-size: 8pt; color: #d97706; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 8px; }
    .card-q { font-size: 11pt; font-weight: 600; line-height: 1.5; }
    .card-back { padding: 14px 20px; border-top: 2px solid #f1f5f9; }
    .answer-label { font-size: 8pt; color: #94a3b8; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 6px; }
    .card-a { font-size: 10pt; color: #334155; line-height: 1.6; }
    .footer { text-align: center; margin-top: 32px; font-size: 8pt; color: #94a3b8; }
    @media print {
      body { background: white; padding: 20px; }
      .card { box-shadow: none; border: 1px solid #e2e8f0; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Study Flashcards</h1>
    <p>${memo.title} &nbsp;·&nbsp; ${cards.length} cards &nbsp;·&nbsp; Generated by Casify AI</p>
  </div>
  <div class="grid">
    ${cards.map((c, i) => `
      <div class="card">
        <div class="card-front">
          <div class="card-num">Card ${i + 1} / ${cards.length}</div>
          <div class="card-q">${c.front}</div>
        </div>
        <div class="card-back">
          <div class="answer-label">Answer</div>
          <div class="card-a">${c.back}</div>
        </div>
      </div>
    `).join('')}
  </div>
  <div class="footer">Casify AI Legal Partner &nbsp;·&nbsp; For educational purposes only</div>
</body>
</html>`);
    win.document.close();
    setTimeout(() => win.print(), 500);
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white w-full max-w-2xl max-h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-navy-900 p-2 rounded-lg">
              <Layers className="w-5 h-5 text-gold-500" />
            </div>
            <div>
              <h2 className="font-serif text-xl font-bold text-navy-900">Flashcards</h2>
              <p className="text-xs text-gray-500">{cards.length > 0 ? `${cards.length} cards generated` : 'AI-generated study cards'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {cards.length > 0 && (
              <>
                <button
                  onClick={() => setViewMode(v => v === 'grid' ? 'study' : 'grid')}
                  className="text-xs px-3 py-1.5 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 transition-all"
                >
                  {viewMode === 'grid' ? 'Study Mode' : 'Grid View'}
                </button>
                <button onClick={handlePrintCards} className="text-xs px-3 py-1.5 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 transition-all flex items-center gap-1">
                  <Download className="w-3.5 h-3.5" /> PDF
                </button>
              </>
            )}
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors p-1">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">

          {/* Generate button */}
          {cards.length === 0 && (
            <div className="text-center py-8">
              {error && <p className="text-red-500 text-sm mb-4">{error}</p>}
              <div className="mb-6 text-gray-500">
                <Layers className="w-12 h-12 mx-auto mb-3 text-navy-200" />
                <p className="font-medium text-navy-900">Generate study flashcards</p>
                <p className="text-sm mt-1">AI will create 12-15 cards covering key terms, IRAC elements, legal principles, and risks from this case.</p>
              </div>
              <button
                onClick={handleGenerate}
                disabled={isLoading}
                className="bg-navy-900 text-white px-8 py-3.5 rounded-xl font-bold hover:bg-navy-800 transition-all shadow-md flex items-center gap-2 mx-auto disabled:opacity-70"
              >
                {isLoading ? <><Loader2 className="w-5 h-5 animate-spin" />Generating cards...</> : <><Layers className="w-5 h-5" />Generate Flashcards</>}
              </button>
            </div>
          )}

          {/* Study Mode */}
          {cards.length > 0 && viewMode === 'study' && (
            <div className="flex flex-col items-center">
              {/* Progress */}
              <div className="w-full flex items-center justify-between mb-4 text-sm text-gray-500">
                <span>Card {currentIdx + 1} of {cards.length}</span>
                <div className="flex gap-1">
                  {cards.map((_, i) => (
                    <button
                      key={i}
                      onClick={() => { setIsFlipped(false); setCurrentIdx(i); }}
                      className={`w-2 h-2 rounded-full transition-all ${i === currentIdx ? 'bg-navy-900 w-4' : 'bg-gray-300'}`}
                    />
                  ))}
                </div>
                <button onClick={() => { setIsFlipped(false); setCurrentIdx(0); }} className="flex items-center gap-1 text-gray-400 hover:text-navy-900 transition-colors">
                  <RotateCcw className="w-3.5 h-3.5" /> Reset
                </button>
              </div>

              {/* Flip Card */}
              <div
                className="w-full cursor-pointer select-none"
                style={{ perspective: '1000px' }}
                onClick={() => setIsFlipped(f => !f)}
              >
                <div
                  className="relative w-full transition-transform duration-500"
                  style={{
                    transformStyle: 'preserve-3d',
                    transform: isFlipped ? 'rotateY(180deg)' : 'rotateY(0deg)',
                    minHeight: '220px'
                  }}
                >
                  {/* Front */}
                  <div
                    className="absolute inset-0 w-full bg-navy-900 rounded-2xl p-8 flex flex-col justify-center items-center text-center"
                    style={{ backfaceVisibility: 'hidden' }}
                  >
                    <span className="text-[10px] text-gold-400 uppercase tracking-widest mb-3 font-bold">Question</span>
                    <p className="text-white text-xl font-serif font-bold leading-relaxed">{cards[currentIdx]?.front}</p>
                    <span className="text-gray-500 text-xs mt-6">Click to reveal answer</span>
                  </div>

                  {/* Back */}
                  <div
                    className="absolute inset-0 w-full bg-gold-600 rounded-2xl p-8 flex flex-col justify-center items-center text-center"
                    style={{ backfaceVisibility: 'hidden', transform: 'rotateY(180deg)' }}
                  >
                    <span className="text-[10px] text-white/70 uppercase tracking-widest mb-3 font-bold">Answer</span>
                    <p className="text-white text-lg font-medium leading-relaxed">{cards[currentIdx]?.back}</p>
                  </div>
                </div>
              </div>

              {/* Navigation */}
              <div className="flex items-center gap-4 mt-6">
                <button
                  onClick={goPrev}
                  disabled={currentIdx === 0}
                  className="w-12 h-12 rounded-full border-2 border-gray-200 flex items-center justify-center text-gray-500 hover:border-navy-900 hover:text-navy-900 transition-all disabled:opacity-30"
                >
                  <ChevronLeft className="w-5 h-5" />
                </button>
                <span className="text-sm text-gray-400 w-20 text-center">
                  {isFlipped ? 'Showing answer' : 'Click to flip'}
                </span>
                <button
                  onClick={goNext}
                  disabled={currentIdx === cards.length - 1}
                  className="w-12 h-12 rounded-full border-2 border-gray-200 flex items-center justify-center text-gray-500 hover:border-navy-900 hover:text-navy-900 transition-all disabled:opacity-30"
                >
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}

          {/* Grid View */}
          {cards.length > 0 && viewMode === 'grid' && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {cards.map((card, i) => (
                <div
                  key={i}
                  className="border border-gray-200 rounded-xl overflow-hidden hover:shadow-md transition-shadow cursor-pointer"
                  onClick={() => { setCurrentIdx(i); setViewMode('study'); setIsFlipped(false); }}
                >
                  <div className="bg-navy-900 px-4 py-3">
                    <span className="text-[10px] text-gold-400 uppercase tracking-wide font-bold">Card {i + 1}</span>
                    <p className="text-white text-sm font-semibold mt-1 line-clamp-2">{card.front}</p>
                  </div>
                  <div className="px-4 py-3 bg-white">
                    <p className="text-gray-600 text-xs line-clamp-3">{card.back}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FlashcardsModal;
